<?php

use Illuminate\Database\Seeder;

class LocationsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('locations')->delete();
        DB::table('locations')->insert([

            //Chamkar Mon

            [
                'name' => 'Tonle Basak',
                'description' => 'Tonle Basak',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chamkar Mon')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Boeng Keng Kang 1',
                'description' => 'Boeng Keng Kang 1',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chamkar Mon')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Boeng Keng Kang 2',
                'description' => 'Boeng Keng Kang 2',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chamkar Mon')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Boeng Keng Kang 3',
                'description' => 'Boeng Keng Kang 3',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chamkar Mon')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Olympic',
                'description' => 'Olympic',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chamkar Mon')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Tuol Svay Prey Ti 1',
                'description' => 'Tuol Svay Prey Ti 1',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chamkar Mon')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Tuol Svay Prey Ti 2',
                'description' => 'Tuol Svay Prey Ti 2',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chamkar Mon')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Tumnob Tuek',
                'description' => 'Tumnob Tuek',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chamkar Mon')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Tuol Tumpung Ti 2',
                'description' => 'Tuol Tumpung Ti 2',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chamkar Mon')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Tuol Tumpung Ti 1',
                'description' => 'Tuol Tumpung Ti 1',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chamkar Mon')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Boeng Tabaek',
                'description' => 'Boeng Tabaek',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chamkar Mon')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phsar Daeum Thkov',
                'description' => 'Phsar Daeum Thkov',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chamkar Mon')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Doun Penh

            [
                'name' => 'Srah Chak',
                'description' => 'Srah Chak',
                'state_id' =>  DB::table('states')->select('id')->where('name','Doun Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Wat Phnom',
                'description' => 'Wat Phnom',
                'state_id' =>  DB::table('states')->select('id')->where('name','Doun Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phsah Chas',
                'description' => 'Phsah Chas',
                'state_id' =>  DB::table('states')->select('id')->where('name','Doun Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phsah Kandal I',
                'description' => 'Phsah Kandal I',
                'state_id' =>  DB::table('states')->select('id')->where('name','Doun Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phsah Kandal II',
                'description' => 'Phsah Kandal II',
                'state_id' =>  DB::table('states')->select('id')->where('name','Doun Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chey Chomneas',
                'description' => 'Chey Chomneas',
                'state_id' =>  DB::table('states')->select('id')->where('name','Doun Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chaktomuk',
                'description' => 'Chaktomuk',
                'state_id' =>  DB::table('states')->select('id')->where('name','Doun Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phsah Thmey I',
                'description' => 'Phsah Thmey I',
                'state_id' =>  DB::table('states')->select('id')->where('name','Doun Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phsah Thmey II',
                'description' => 'Phsah Thmey II',
                'state_id' =>  DB::table('states')->select('id')->where('name','Doun Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phsah Thmey III',
                'description' => 'Phsah Thmey III',
                'state_id' =>  DB::table('states')->select('id')->where('name','Doun Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Boeng Raing',
                'description' => 'Boeng Raing',
                'state_id' =>  DB::table('states')->select('id')->where('name','Doun Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Prampir Meakkakra

            [
                'name' => 'Monourom',
                'description' => 'Monourom',
                'state_id' =>  DB::table('states')->select('id')->where('name','Prampir Meakkakra')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Mittakpheap',
                'description' => 'Mittakpheap',
                'state_id' =>  DB::table('states')->select('id')->where('name','Prampir Meakkakra')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Veal Vong',
                'description' => 'Veal Vong',
                'state_id' =>  DB::table('states')->select('id')->where('name','Prampir Meakkakra')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ou Ruessei Ti Muoy',
                'description' => 'Ou Ruessei Ti Muoy',
                'state_id' =>  DB::table('states')->select('id')->where('name','Prampir Meakkakra')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ou Ruessei Ti Pir',
                'description' => 'Ou Ruessei Ti Pir',
                'state_id' =>  DB::table('states')->select('id')->where('name','Prampir Meakkakra')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ou Ruessei Ti Bei',
                'description' => 'Ou Ruessei Ti Bei',
                'state_id' =>  DB::table('states')->select('id')->where('name','Prampir Meakkakra')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ou Ruessei Ti Buon',
                'description' => 'Ou Ruessei Ti Buon',
                'state_id' =>  DB::table('states')->select('id')->where('name','Prampir Meakkakra')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Boeng Prolit',
                'description' => 'Boeng Prolit',
                'state_id' =>  DB::table('states')->select('id')->where('name','Prampir Meakkakra')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Tuol Kouk

            [
                'name' => 'Boeng Kak Ti Muoy',
                'description' => 'Boeng Kak Ti Muoy',
                'state_id' =>  DB::table('states')->select('id')->where('name','Tuol Kouk')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Boeng Kak Ti Pir',
                'description' => 'Boeng Kak Ti Pir',
                'state_id' =>  DB::table('states')->select('id')->where('name','Tuol Kouk')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phsar Depou Ti Muoy',
                'description' => 'Phsar Depou Ti Muoy',
                'state_id' =>  DB::table('states')->select('id')->where('name','Tuol Kouk')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phsar Depou Ti Pir',
                'description' => 'Phsar Depou Ti Pir',
                'state_id' =>  DB::table('states')->select('id')->where('name','Tuol Kouk')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phsar Depou Ti Bei',
                'description' => 'Phsar Depou Ti Bei',
                'state_id' =>  DB::table('states')->select('id')->where('name','Tuol Kouk')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => "Tuek L'ak Ti Muoy",
                'description' => "Tuek L'ak Ti Muoy",
                'state_id' =>  DB::table('states')->select('id')->where('name','Tuol Kouk')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => "Tuek L'ak Ti Pir",
                'description' => "Tuek L'ak Ti Bei",
                'state_id' =>  DB::table('states')->select('id')->where('name','Tuol Kouk')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phsar Daeum Kor',
                'description' => 'Phsar Daeum Kor',
                'state_id' =>  DB::table('states')->select('id')->where('name','Tuol Kouk')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Boeng Salang',
                'description' => 'Boeng Salang',
                'state_id' =>  DB::table('states')->select('id')->where('name','Tuol Kouk')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Dangkao

            [
                'name' => 'Dangkao',
                'description' => 'Dangkao',
                'state_id' =>  DB::table('states')->select('id')->where('name','Dangkao')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Pong Tuek',
                'description' => 'Pong Tuek',
                'state_id' =>  DB::table('states')->select('id')->where('name','Dangkao')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Prey Veaeng',
                'description' => 'Prey Veaeng',
                'state_id' =>  DB::table('states')->select('id')->where('name','Dangkao')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Prey Sa',
                'description' => 'Prey Sa',
                'state_id' =>  DB::table('states')->select('id')->where('name','Dangkao')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krang Pongro',
                'description' => 'Krang Pongro',
                'state_id' =>  DB::table('states')->select('id')->where('name','Dangkao')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Prateah Lang',
                'description' => 'Prateah Lang',
                'state_id' =>  DB::table('states')->select('id')->where('name','Dangkao')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Sak Sampov',
                'description' => 'Sak Sampov',
                'state_id' =>  DB::table('states')->select('id')->where('name','Dangkao')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Cheung Aek',
                'description' => 'Cheung Aek',
                'state_id' =>  DB::table('states')->select('id')->where('name','Dangkao')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kong Noy',
                'description' => 'Kong Noy',
                'state_id' =>  DB::table('states')->select('id')->where('name','Dangkao')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Preaek Kampues',
                'description' => 'Preaek Kampues',
                'state_id' =>  DB::table('states')->select('id')->where('name','Dangkao')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Roluos',
                'description' => 'Roluos',
                'state_id' =>  DB::table('states')->select('id')->where('name','Dangkao')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Spean Thma',
                'description' => 'Spean Thma',
                'state_id' =>  DB::table('states')->select('id')->where('name','Dangkao')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Tien',
                'description' => 'Tien',
                'state_id' =>  DB::table('states')->select('id')->where('name','Dangkao')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Mean Chey

            [
                'name' => 'Stueng Mean Chey',
                'description' => 'Stueng Mean Chey',
                'state_id' =>  DB::table('states')->select('id')->where('name','Mean Chey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Boeng Tumpun',
                'description' => 'Boeng Tumpun',
                'state_id' =>  DB::table('states')->select('id')->where('name','Mean Chey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chak Angrae Leu',
                'description' => 'Chak Angrae Leu',
                'state_id' =>  DB::table('states')->select('id')->where('name','Mean Chey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chak Angrae Kraom',
                'description' => 'Chak Angrae Kraom',
                'state_id' =>  DB::table('states')->select('id')->where('name','Mean Chey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Russey Keo

            [
                'name' => 'Tuol Sangkae',
                'description' => 'Tuol Sangkae',
                'state_id' =>  DB::table('states')->select('id')->where('name','Russey Keo')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Svay Pak',
                'description' => 'Svay Pak',
                'state_id' =>  DB::table('states')->select('id')->where('name','Russey Keo')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kilomaetr Lekh Prammuoy',
                'description' => 'Kilomaetr Lekh Prammuoy',
                'state_id' =>  DB::table('states')->select('id')->where('name','Russey Keo')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ruessei Kaev',
                'description' => 'Ruessei Kaev',
                'state_id' =>  DB::table('states')->select('id')->where('name','Russey Keo')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chrang Chamreh Ti Muoy',
                'description' => 'Chrang Chamreh Ti Muoy',
                'state_id' =>  DB::table('states')->select('id')->where('name','Russey Keo')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chrang Chamreh Ti Pir',
                'description' => 'Chrang Chamreh Ti Pir',
                'state_id' =>  DB::table('states')->select('id')->where('name','Russey Keo')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Sen Sok

            [
                'name' => 'Phnom Penh Thmei',
                'description' => 'Phnom Penh Thmei',
                'state_id' =>  DB::table('states')->select('id')->where('name','Sen Sok')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Tuek Thla',
                'description' => 'Tuek Thla',
                'state_id' =>  DB::table('states')->select('id')->where('name','Sen Sok')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Khmuonh',
                'description' => 'Khmuonh',
                'state_id' =>  DB::table('states')->select('id')->where('name','Sen Sok')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            // Pou Senchey

            [
                'name' => 'Trapeang Krasang',
                'description' => 'Trapeang Krasang',
                'state_id' =>  DB::table('states')->select('id')->where('name','Pou Senchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phleung Chheh Roteh',
                'description' => 'Phleung Chheh Roteh',
                'state_id' =>  DB::table('states')->select('id')->where('name','Pou Senchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chaom Chau',
                'description' => 'Chaom Chau',
                'state_id' =>  DB::table('states')->select('id')->where('name','Pou Senchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kakab',
                'description' => 'Kakab',
                'state_id' =>  DB::table('states')->select('id')->where('name','Pou Senchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Samraong Kraom',
                'description' => 'Samraong Kraom',
                'state_id' =>  DB::table('states')->select('id')->where('name','Pou Senchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krang Thnong',
                'description' => 'Krang Thnong',
                'state_id' =>  DB::table('states')->select('id')->where('name','Pou Senchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Boeng Thum',
                'description' => 'Boeng Thum',
                'state_id' =>  DB::table('states')->select('id')->where('name','Pou Senchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kamboul',
                'description' => 'Kamboul',
                'state_id' =>  DB::table('states')->select('id')->where('name','Pou Senchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kantaok',
                'description' => 'Kantaok',
                'state_id' =>  DB::table('states')->select('id')->where('name','Pou Senchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ovlaok',
                'description' => 'Ovlaok',
                'state_id' =>  DB::table('states')->select('id')->where('name','Pou Senchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Snaor',
                'description' => 'Snaor',
                'state_id' =>  DB::table('states')->select('id')->where('name','Pou Senchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Chrouy Changvar

            [
                'name' => 'Preaek Lieb',
                'description' => 'Preaek Lieb',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chrouy Changvar')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Preaek Ta Sek',
                'description' => 'Preaek Ta Sek',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chrouy Changvar')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chroy Changvar',
                'description' => 'Chroy Changvar',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chrouy Changvar')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Bak Kaeng',
                'description' => 'Bak Kaeng',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chrouy Changvar')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kaoh Dach',
                'description' => 'Kaoh Dach',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chrouy Changvar')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Preaek Pnov

            [
                'name' => 'Ponhea Pon',
                'description' => 'Ponhea Pon',
                'state_id' =>  DB::table('states')->select('id')->where('name','Preaek Pnov')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Preaek Pnov',
                'description' => 'Preaek Pnov',
                'state_id' =>  DB::table('states')->select('id')->where('name','Preaek Pnov')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Samraong',
                'description' => 'Samraong',
                'state_id' =>  DB::table('states')->select('id')->where('name','Preaek Pnov')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kouk Roka',
                'description' => 'Kouk Roka',
                'state_id' =>  DB::table('states')->select('id')->where('name','Preaek Pnov')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ponsang',
                'description' => 'Ponsang',
                'state_id' =>  DB::table('states')->select('id')->where('name','Preaek Pnov')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            // Chbar Ampov

            [
                'name' => 'Preaek Pra',
                'description' => 'Preaek Pra',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chbar Ampov')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chbar Ampot Ti Muoy',
                'description' => 'Chbar Ampot Ti Muoy',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chbar Ampov')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chbar Ampov Ti Pir',
                'description' => 'Chbar Ampov Ti Pir',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chbar Ampov')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Nirouth',
                'description' => 'Nirouth',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chbar Ampov')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kbal Kaoh',
                'description' => 'Kbal Kaoh',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chbar Ampov')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Preaek Aeng',
                'description' => 'Preaek Aeng',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chbar Ampov')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Preaek Thmei',
                'description' => 'Preaek Thmei',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chbar Ampov')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Veal Sbov',
                'description' => 'Veal Sbov',
                'state_id' =>  DB::table('states')->select('id')->where('name','Chbar Ampov')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],


            //Mongkol Borei

            [
                'name' => 'Banteay Neang',
                'description' => 'Banteay Neang',
                'state_id' =>  DB::table('states')->select('id')->where('name','Mongkol Borei')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Bat Trang',
                'description' => 'Bat Trang',
                'state_id' =>  DB::table('states')->select('id')->where('name','Mongkol Borei')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chamnaom',
                'description' => 'Chamnaom',
                'state_id' =>  DB::table('states')->select('id')->where('name','Mongkol Borei')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kouk Ballangk',
                'description' => 'Kouk Ballangk',
                'state_id' =>  DB::table('states')->select('id')->where('name','Mongkol Borei')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Koy Maeng',
                'description' => 'Koy Maeng',
                'state_id' =>  DB::table('states')->select('id')->where('name','Mongkol Borei')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ou Prasat',
                'description' => 'Ou Prasat',
                'state_id' =>  DB::table('states')->select('id')->where('name','Mongkol Borei')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phnum Touch',
                'description' => 'Phnum Touch',
                'state_id' =>  DB::table('states')->select('id')->where('name','Mongkol Borei')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Rohat Tuek',
                'description' => 'Rohat Tuek',
                'state_id' =>  DB::table('states')->select('id')->where('name','Mongkol Borei')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ruessei Kraok',
                'description' => 'Ruessei Kraok',
                'state_id' =>  DB::table('states')->select('id')->where('name','Mongkol Borei')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Sambuor',
                'description' => 'Sambuor',
                'state_id' =>  DB::table('states')->select('id')->where('name','Mongkol Borei')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Soea',
                'description' => 'Soea',
                'state_id' =>  DB::table('states')->select('id')->where('name','Mongkol Borei')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Srah Reang',
                'description' => 'Srah Reang',
                'state_id' =>  DB::table('states')->select('id')->where('name','Mongkol Borei')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ta Lam',
                'description' => 'Ta Lam',
                'state_id' =>  DB::table('states')->select('id')->where('name','Mongkol Borei')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Phnum Srok

            [
                'name' => 'Nam Tau',
                'description' => 'Nam Tau',
                'state_id' =>  DB::table('states')->select('id')->where('name','Phnum Srok')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Poy Char',
                'description' => 'Poy Char',
                'state_id' =>  DB::table('states')->select('id')->where('name','Phnum Srok')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phnum Dei',
                'description' => 'Phnum Dei',
                'state_id' =>  DB::table('states')->select('id')->where('name','Phnum Srok')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ponley',
                'description' => 'Ponley',
                'state_id' =>  DB::table('states')->select('id')->where('name','Phnum Srok')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Spean Sraeng',
                'description' => 'Spean Sraeng',
                'state_id' =>  DB::table('states')->select('id')->where('name','Phnum Srok')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Srah Chik',
                'description' => 'Srah Chik',
                'state_id' =>  DB::table('states')->select('id')->where('name','Phnum Srok')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Preah Netr Preah

            [
                'name' => 'Chnuor Mean Chey',
                'description' => 'Chnuor Mean Chey',
                'state_id' =>  DB::table('states')->select('id')->where('name','Preah Netr Preah')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chob Vari',
                'description' => 'Chob Vari',
                'state_id' =>  DB::table('states')->select('id')->where('name','Preah Netr Preah')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phnum Lieb',
                'description' => 'Phnum Lieb',
                'state_id' =>  DB::table('states')->select('id')->where('name','Preah Netr Preah')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Prasat',
                'description' => 'Prasat',
                'state_id' =>  DB::table('states')->select('id')->where('name','Preah Netr Preah')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Preah Netr Preah',
                'description' => 'Preah Netr Preah',
                'state_id' =>  DB::table('states')->select('id')->where('name','Preah Netr Preah')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Rohal',
                'description' => 'Rohal',
                'state_id' =>  DB::table('states')->select('id')->where('name','Preah Netr Preah')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Tean Kam',
                'description' => 'Tean Kam',
                'state_id' =>  DB::table('states')->select('id')->where('name','Preah Netr Preah')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Tuek Chour',
                'description' => 'Tuek Chour',
                'state_id' =>  DB::table('states')->select('id')->where('name','Preah Netr Preah')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Bos Sbov',
                'description' => 'Bos Sbov',
                'state_id' =>  DB::table('states')->select('id')->where('name','Preah Netr Preah')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Ou Chrov

            [
                'name' => 'Changha',
                'description' => 'Changha',
                'state_id' =>  DB::table('states')->select('id')->where('name','Ou Chrov')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Koub',
                'description' => 'Koub',
                'state_id' =>  DB::table('states')->select('id')->where('name','Ou Chrov')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kuttasat',
                'description' => 'Kuttasat',
                'state_id' =>  DB::table('states')->select('id')->where('name','Ou Chrov')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Samraong',
                'description' => 'Samraong',
                'state_id' =>  DB::table('states')->select('id')->where('name','Ou Chrov')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Souphi',
                'description' => 'Souphi',
                'state_id' =>  DB::table('states')->select('id')->where('name','Ou Chrov')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Soengh',
                'description' => 'Soengh',
                'state_id' =>  DB::table('states')->select('id')->where('name','Ou Chrov')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ou Beichaon',
                'description' => 'Ou Beichaon',
                'state_id' =>  DB::table('states')->select('id')->where('name','Ou Chrov')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Krong Serei Saophoan

            [
                'name' => 'Kampong Svay',
                'description' => 'Kampong Svay',
                'state_id' =>  DB::table('states')->select('id')->where('name','Krong Serei Saophoan')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kaoh Pong Satv',
                'description' => 'Kaoh Pong Satv',
                'state_id' =>  DB::table('states')->select('id')->where('name','Krong Serei Saophoan')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Mkak',
                'description' => 'Mkak',
                'state_id' =>  DB::table('states')->select('id')->where('name','Krong Serei Saophoan')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ou Ambel',
                'description' => 'Ou Ambel',
                'state_id' =>  DB::table('states')->select('id')->where('name','Krong Serei Saophoan')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phniet',
                'description' => 'Phniet',
                'state_id' =>  DB::table('states')->select('id')->where('name','Krong Serei Saophoan')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Preah Ponlea',
                'description' => 'Preah Ponlea',
                'state_id' =>  DB::table('states')->select('id')->where('name','Krong Serei Saophoan')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Tuek Thla',
                'description' => 'Tuek Thla',
                'state_id' =>  DB::table('states')->select('id')->where('name','Krong Serei Saophoan')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Thma Puok

            [
                'name' => 'Banteay Chhmar',
                'description' => 'Banteay Chhmar',
                'state_id' =>  DB::table('states')->select('id')->where('name','Thma Puok')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kouk Kakthen',
                'description' => 'Kouk Kakthen',
                'state_id' =>  DB::table('states')->select('id')->where('name','Thma Puok')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kouk Romiet',
                'description' => 'Kouk Romiet',
                'state_id' =>  DB::table('states')->select('id')->where('name','Thma Puok')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kumru',
                'description' => 'Kumru',
                'state_id' =>  DB::table('states')->select('id')->where('name','Thma Puok')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phum Thmei',
                'description' => 'Phum Thmei',
                'state_id' =>  DB::table('states')->select('id')->where('name','Thma Puok')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Thma Puok',
                'description' => 'Thma Puok',
                'state_id' =>  DB::table('states')->select('id')->where('name','Thma Puok')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Svay Chek

            [
                'name' => 'Phkoam',
                'description' => 'Phkoam',
                'state_id' =>  DB::table('states')->select('id')->where('name','Svay Chek')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Roluos',
                'description' => 'Roluos',
                'state_id' =>  DB::table('states')->select('id')->where('name','Svay Chek')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Sarongk',
                'description' => 'Sarongk',
                'state_id' =>  DB::table('states')->select('id')->where('name','Svay Chek')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Sla Kram',
                'description' => 'Sla Kram',
                'state_id' =>  DB::table('states')->select('id')->where('name','Svay Chek')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Svay Chek',
                'description' => 'Svay Chek',
                'state_id' =>  DB::table('states')->select('id')->where('name','Svay Chek')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ta Baen',
                'description' => 'Ta Baen',
                'state_id' =>  DB::table('states')->select('id')->where('name','Svay Chek')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ta Phou',
                'description' => 'Ta Phou',
                'state_id' =>  DB::table('states')->select('id')->where('name','Svay Chek')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Treas',
                'description' => 'Treas',
                'state_id' =>  DB::table('states')->select('id')->where('name','Svay Chek')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Malai

            [
                'name' => 'Boeng Beng',
                'description' => 'Boeng Beng',
                'state_id' =>  DB::table('states')->select('id')->where('name','Malai')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Malai',
                'description' => 'Malai',
                'state_id' =>  DB::table('states')->select('id')->where('name','Malai')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ou Sampor',
                'description' => 'Ou Sampor',
                'state_id' =>  DB::table('states')->select('id')->where('name','Malai')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ou Sralau',
                'description' => 'Ou Sralau',
                'state_id' =>  DB::table('states')->select('id')->where('name','Malai')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ta Kong',
                'description' => 'Ta Kong',
                'state_id' =>  DB::table('states')->select('id')->where('name','Malai')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Tuol Pongro',
                'description' => 'Tuol Pongro',
                'state_id' =>  DB::table('states')->select('id')->where('name','Malai')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Krong Paoy Paet

            [
                'name' => 'Nimit',
                'description' => 'Nimit',
                'state_id' =>  DB::table('states')->select('id')->where('name','Krong Paoy Paet')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Paoy Paet',
                'description' => 'Paoy Paet',
                'state_id' =>  DB::table('states')->select('id')->where('name','Krong Paoy Paet')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

        ]);
    }
}
