<?php

use Illuminate\Database\Seeder;

class StatesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('states')->delete();
        DB::table('states')->insert([

            // Phnom Penh
            [
                'name' => 'Chamkar Mon',
                'description' => 'Chamkar Mon',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Phnom Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Doun Penh',
                'description' => 'Doun Penh',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Phnom Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Prampir Meakkakra',
                'description' => 'Prampir Meakkakra',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Phnom Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Tuol Kouk',
                'description' => 'Tuol Kouk',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Phnom Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Dangkao',
                'description' => 'Dangkao',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Phnom Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Mean Chey',
                'description' => 'Mean Chey',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Phnom Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Russey Keo',
                'description' => 'Russey Keo',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Phnom Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Sen Sok',
                'description' => 'Sen Sok',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Phnom Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Pou Senchey',
                'description' => 'Pou Senchey',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Phnom Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chrouy Changvar',
                'description' => 'Chrouy Changvar',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Phnom Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Preaek Pnov',
                'description' => 'Preaek Pnov',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Phnom Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chbar Ampov',
                'description' => 'Chbar Ampov',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Phnom Penh')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            // Banteay Meanchey

            [
                'name' => 'Mongkol Borei',
                'description' => 'Mongkol Borei',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Banteay Meanchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phnum Srok',
                'description' => 'Phnum Srok',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Banteay Meanchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Preah Netr Preah',
                'description' => 'Preah Netr Preah',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Banteay Meanchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ou Chrov',
                'description' => 'Ou Chrov',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Banteay Meanchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Serei Saophoan',
                'description' => 'Krong Serei Saophoan',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Banteay Meanchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Thma Puok',
                'description' => 'Thma Puok',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Banteay Meanchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Svay Chek',
                'description' => 'Svay Chek',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Banteay Meanchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Malai',
                'description' => 'Malai',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Banteay Meanchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Paoy Paet',
                'description' => 'Krong Paoy Paet',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Banteay Meanchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            // Battambang

            [
                'name' => 'Banan',
                'description' => 'Banan',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Battambang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Thma Koul',
                'description' => 'Thma Koul',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Battambang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Battambang',
                'description' => 'Krong Battambang',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Battambang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Bavel',
                'description' => 'Bavel',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Battambang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ek Phnom',
                'description' => 'Ek Phnom',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Battambang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Moung Ruessi',
                'description' => 'Moung Ruessi',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Battambang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Rotanak Mondol',
                'description' => 'Rotanak Mondol',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Battambang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Sangkae',
                'description' => 'Sangkae',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Battambang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Samlout',
                'description' => 'Samlout',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Battambang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Sampov Loun',
                'description' => 'Sampov Loun',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Battambang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phnum Proek',
                'description' => 'Phnum Proek',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Battambang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kamrieng',
                'description' => 'Kamrieng',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Battambang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Koas Krala',
                'description' => 'Koas Krala',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Battambang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Rukhak Kiri',
                'description' => 'Rukhak Kiri',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Battambang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Kampong Cham

            [
                'name' => 'Batheay',
                'description' => 'Batheay',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Cham')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chamkar Leu',
                'description' => 'Chamkar Leu',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Cham')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Cheung Prey',
                'description' => 'Cheung Prey',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Cham')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Kampong Cham',
                'description' => 'Krong Kampong Cham',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Cham')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kampong Siem',
                'description' => 'Kampong Siem',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Cham')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kang Meas',
                'description' => 'Kang Meas',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Cham')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Koh Sotin',
                'description' => 'Koh Sotin',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Cham')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Prey Chhor',
                'description' => 'Prey Chhor',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Cham')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Srey Santhor',
                'description' => 'Srey Santhor',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Cham')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Stueng Trang',
                'description' => 'Stueng Trang',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Cham')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Kampong Chhnang

            [
                'name' => 'Baribour',
                'description' => 'Baribour',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Chhnang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chol Kiri',
                'description' => 'Chol Kiri',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Chhnang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Kampong Chhnang',
                'description' => 'Krong Kampong Chhnang',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Chhnang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kampong Leaeng',
                'description' => 'Kampong Leaeng',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Chhnang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kampong Tralach',
                'description' => 'Kampong Tralach',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Chhnang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => "Rolea B'ier",
                'description' => "Rolea B'ier",
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Chhnang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Sameakki Mean Chey',
                'description' => 'Sameakki Mean Chey',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Chhnang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Tuek Phos',
                'description' => 'Tuek Phos',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Chhnang')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Kampong Speu

            [
                'name' => 'Basedth',
                'description' => 'Basedth',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Speu')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Chbar Mon',
                'description' => 'Krong Chbar Mon',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Speu')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kong Pisei',
                'description' => 'Kong Pisei',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Speu')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Aoral',
                'description' => 'Aoral',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Speu')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Odongk',
                'description' => 'Odongk',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Speu')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phnom Sruoch',
                'description' => 'Phnom Sruoch',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Speu')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Samraong Tong',
                'description' => 'Samraong Tong',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Speu')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Thpong',
                'description' => 'Thpong',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Speu')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Kampong Thom

            [
                'name' => 'Baray',
                'description' => 'Baray',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Thom')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kampong Svay',
                'description' => 'Kampong Svay',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Thom')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Stueng Saen',
                'description' => 'Krong Stueng Saen',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Thom')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Prasat Balangk',
                'description' => 'Prasat Balangk',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Thom')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Prasat Sambour',
                'description' => 'Prasat Sambour',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Thom')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Sandaan',
                'description' => 'Sandaan',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Thom')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Santuk',
                'description' => 'Santuk',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Thom')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Stoung',
                'description' => 'Stoung',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampong Thom')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Kampot

            [
                'name' => 'Angkor Chey',
                'description' => 'Angkor Chey',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampot')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Banteay Meas',
                'description' => 'Banteay Meas',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampot')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chhuk',
                'description' => 'Chhuk',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampot')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chum Kiri',
                'description' => 'Chum Kiri',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampot')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Dang Tong',
                'description' => 'Dang Tong',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampot')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kampong Trach',
                'description' => 'Kampong Trach',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampot')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Tuek Chhou',
                'description' => 'Tuek Chhou',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampot')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Kampot',
                'description' => 'Krong Kampot',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kampot')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Kandal

            [
                'name' => 'Kandal Stueng',
                'description' => 'Kandal Stueng',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kandal')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kien Svay',
                'description' => 'Kien Svay',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kandal')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Khsach Kandal',
                'description' => 'Khsach Kandal',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kandal')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kaoh Thum',
                'description' => 'Kaoh Thum',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kandal')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Leuk Daek',
                'description' => 'Leuk Daek',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kandal')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Lvea Aem',
                'description' => 'Lvea Aem',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kandal')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Mukh Kampul',
                'description' => 'Mukh Kampul',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kandal')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Angk Snuol',
                'description' => 'Angk Snuol',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kandal')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ponhea Lueu',
                'description' => 'Ponhea Lueu',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kandal')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => "S'ang",
                'description' => "S'ang",
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kandal')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Ta Khmau',
                'description' => 'Krong Ta Khmau',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kandal')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Koh Kong

            [
                'name' => 'Botum Sakor',
                'description' => 'Botum Sakor',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Koh Kong')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kiri Sakor',
                'description' => 'Kiri Sakor',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Koh Kong')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Khemara Phoumin',
                'description' => 'Krong Khemara Phoumin',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Koh Kong')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Smach Mean Chey',
                'description' => 'Smach Mean Chey',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Koh Kong')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Mondol Seima',
                'description' => 'Mondol Seima',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Koh Kong')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Srae Ambel',
                'description' => 'Srae Ambel',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Koh Kong')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Thma Bang',
                'description' => 'Thma Bang',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Koh Kong')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Kratié

            [
                'name' => 'Chhloung',
                'description' => 'Chhloung',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kratié')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Kracheh',
                'description' => 'Krong Kracheh',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kratié')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Preaek Prasab',
                'description' => 'Preaek Prasab',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kratié')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Sambour',
                'description' => 'Sambour',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kratié')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Snuol',
                'description' => 'Snuol',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kratié')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chitr Borie',
                'description' => 'Chitr Borie',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kratié')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Mondulkiri

            [
                'name' => 'Kaev Seima',
                'description' => 'Kaev Seima',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Mondulkiri')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kaoh Nheaek',
                'description' => 'Kaoh Nheaek',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Mondulkiri')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ou Reang',
                'description' => 'Ou Reang',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Mondulkiri')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Pechr Chenda',
                'description' => 'Pechr Chenda',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Mondulkiri')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Saen Monourom',
                'description' => 'Krong Saen Monourom',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Mondulkiri')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Oddar Meanchey

            [
                'name' => 'Anlong Veaeng',
                'description' => 'Anlong Veaeng',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Oddar Meanchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Banteay Ampil',
                'description' => 'Banteay Ampil',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Oddar Meanchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chong Kal',
                'description' => 'Chong Kal',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Oddar Meanchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Samraong',
                'description' => 'Krong Samraong',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Oddar Meanchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Trapeang Prasat',
                'description' => 'Trapeang Prasat',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Oddar Meanchey')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Preah Vihear

            [
                'name' => 'Chey Saen',
                'description' => 'Chey Saen',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Preah Vihear')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chhaeb',
                'description' => 'Chhaeb',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Preah Vihear')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Choam Khsant',
                'description' => 'Choam Khsant',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Preah Vihear')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kuleaen',
                'description' => 'Kuleaen',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Preah Vihear')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Rovieng',
                'description' => 'Rovieng',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Preah Vihear')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Sangkom Thmei',
                'description' => 'Sangkom Thmei',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Preah Vihear')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Tbaeng Mean Chey',
                'description' => 'Tbaeng Mean Chey',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Preah Vihear')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Pursat

            [
                'name' => 'Bakan',
                'description' => 'Bakan',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Pursat')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kandieng',
                'description' => 'Kandieng',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Pursat')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krakor',
                'description' => 'Krakor',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Pursat')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phnum Kravanh',
                'description' => 'Phnum Kravanh',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Pursat')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Pursat',
                'description' => 'Krong Pursat',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Pursat')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Veal Veaeng',
                'description' => 'Veal Veaeng',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Pursat')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Prey Veng

            [
                'name' => 'Ba Phnum',
                'description' => 'Ba Phnum',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Prey Veng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kamchay Mear',
                'description' => 'Kamchay Mear',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Prey Veng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kampong Trabaek',
                'description' => 'Kampong Trabaek',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Prey Veng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kanhchriech',
                'description' => 'Kanhchriech',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Prey Veng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Me Sang',
                'description' => 'Me Sang',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Prey Veng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Peam Chor',
                'description' => 'Peam Chor',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Prey Veng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Peam Ro',
                'description' => 'Peam Ro',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Prey Veng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Pea Reang',
                'description' => 'Pea Reang',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Prey Veng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Preah Sdach',
                'description' => 'Preah Sdach',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Prey Veng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Prey Veaeng',
                'description' => 'Krong Prey Veaeng',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Prey Veng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kampong Leav',
                'description' => 'Kampong Leav',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Prey Veng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Sithor Kandal',
                'description' => 'Sithor Kandal',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Prey Veng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Ratanakiri

            [
                'name' => 'Andoung Meas',
                'description' => 'Andoung Meas',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Ratanakiri')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Banlung',
                'description' => 'Krong Banlung',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Ratanakiri')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Bar Kaev',
                'description' => 'Bar Kaev',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Ratanakiri')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Koun Mom',
                'description' => 'Koun Mom',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Ratanakiri')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Lumphat',
                'description' => 'Lumphat',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Ratanakiri')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ou Chum',
                'description' => 'Ou Chum',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Ratanakiri')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ou Ya Dav',
                'description' => 'Ou Ya Dav',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Ratanakiri')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ta Veaeng',
                'description' => 'Ta Veaeng',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Ratanakiri')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Veun Sai',
                'description' => 'Veun Sai',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Ratanakiri')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Siem Reap

            [
                'name' => 'Angkor Chum',
                'description' => 'Angkor Chum',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Siem Reap')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Angkor Thom',
                'description' => 'Angkor Thom',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Siem Reap')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Banteay Srei',
                'description' => 'Banteay Srei',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Siem Reap')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chi Kraeng',
                'description' => 'Chi Kraeng',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Siem Reap')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kralanh',
                'description' => 'Kralanh',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Siem Reap')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Puok',
                'description' => 'Puok',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Siem Reap')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Prasat Bakong',
                'description' => 'Prasat Bakong',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Siem Reap')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Siem Reap',
                'description' => 'Krong Siem Reap',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Siem Reap')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Sout Nikom',
                'description' => 'Sout Nikom',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Siem Reap')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Srei Snam',
                'description' => 'Srei Snam',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Siem Reap')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Svay Leu',
                'description' => 'Svay Leu',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Siem Reap')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Varin',
                'description' => 'Varin',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Siem Reap')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Stung Treng

            [
                'name' => 'Sesan',
                'description' => 'Sesan',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Stung Treng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Siem Bouk',
                'description' => 'Siem Bouk',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Stung Treng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Siem Pang',
                'description' => 'Siem Pang',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Stung Treng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Stung Treng',
                'description' => 'Krong Stung Treng',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Stung Treng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Thala Barivat',
                'description' => 'Thala Barivat',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Stung Treng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Svay Rieng

            [
                'name' => 'Chantrea',
                'description' => 'Chantrea',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Svay Rieng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kampong Rou',
                'description' => 'Kampong Rou',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Svay Rieng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Rumduol',
                'description' => 'Rumduol',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Svay Rieng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Romeas Haek',
                'description' => 'Romeas Haek',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Svay Rieng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Svay Chrum',
                'description' => 'Svay Chrum',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Svay Rieng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Svay Rieng',
                'description' => 'Krong Svay Rieng',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Svay Rieng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Svay Teab',
                'description' => 'Svay Teab',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Svay Rieng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Bavet',
                'description' => 'Bavet',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Svay Rieng')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Takéo

            [
                'name' => 'Angkor Borei',
                'description' => 'Angkor Borei',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Takéo')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Bati',
                'description' => 'Bati',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Takéo')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Bourei Cholsar',
                'description' => 'Bourei Cholsar',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Takéo')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kiri Vong',
                'description' => 'Kiri Vong',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Takéo')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kaoh Andaet',
                'description' => 'Kaoh Andaet',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Takéo')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Prey Kabbas',
                'description' => 'Prey Kabbas',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Takéo')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Samraong',
                'description' => 'Samraong',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Takéo')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Doun Kaev',
                'description' => 'Krong Doun Kaev',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Takéo')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Tram Ka',
                'description' => 'Tram Ka',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Takéo')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Treang',
                'description' => 'Treang',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Takéo')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Kep

            [
                'name' => "Damnak Chang'aeur",
                'description' => "Damnak Chang'aeur",
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kep')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Kep',
                'description' => 'Krong Kep',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Kep')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Pailin

            [
                'name' => 'Krong Pailin',
                'description' => 'Krong Pailin',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Pailin')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Sala Krau',
                'description' => 'Sala Krau',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Pailin')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Preah Sihanouk

            [
                'name' => 'Krong Preah Sihanouk',
                'description' => 'Krong Preah Sihanouk',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Preah Sihanouk')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Prey Nob',
                'description' => 'Prey Nob',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Preah Sihanouk')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Stueng Hav',
                'description' => 'Stueng Hav',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Preah Sihanouk')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kampong Seila',
                'description' => 'Kampong Seila',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Preah Sihanouk')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            //Tboung Khmum

            [
                'name' => 'Dambae',
                'description' => 'Dambae',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Tboung Khmum')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krouch Chhmar',
                'description' => 'Krouch Chhmar',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Tboung Khmum')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Memot',
                'description' => 'Memot',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Tboung Khmum')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ou Reang Ov',
                'description' => 'Ou Reang Ov',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Tboung Khmum')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ponhea Kraek',
                'description' => 'Ponhea Kraek',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Tboung Khmum')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Tboung Khmum',
                'description' => 'Tboung Khmum',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Tboung Khmum')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Krong Suong',
                'description' => 'Krong Suong',
                'country_id' =>  DB::table('countries')->select('id')->where('name','Tboung Khmum')->first()->id,
                'status' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],


        ]);
    }
}
